### ISSUE TITLE
ERROR TypeError: Cannot read property 'minBarLength' of undefined

### ISSUE THREAD

**Issue by diogopaludo** [datavisyn/chartjs-chart-box-and-violin-plot#58] opened 2019-11-14 00:12 UTC
Since updating Chart.js and chartjs-chart-box-and-violin-plot I'm getting this error:

DadosComponent.html:37 ERROR TypeError: Cannot read property 'minBarLength' of undefined
    at ChartElement.calculateBarValuePixels (Chart.js:5042)
    at ChartElement._updateElementGeometry (Chart.js:4937)
    at ChartElement._updateElementGeometry (Chart.BoxPlot.js:1052)
    at ChartElement.updateElement (Chart.js:4922)
    at ChartElement.updateElement (Chart.BoxPlot.js:992)
    at ChartElement.update (Chart.js:4895)
    at ChartElement._update (Chart.js:3831)
    at ChartElement.reset (Chart.js:3733)
    at Chart.js:9638
    at Object.each (Chart.js:2227)

I'm using this in a Angular project. These are the versions:
- "chart.js": "^2.9.2",
- "chartjs-chart-box-and-violin-plot": "^2.1.0",
- "@types/chart.js": "^2.8.11",

Is this a version compatibility problem with Chart.js? Should I downgrade for now?

**Comment by sgratzl** [comment] 2019-11-14 13:56
Duplicate of #53 

there is already a bugfix in the current develop branch that will be released soon (@lehnerchristian). Till then you can either install the develop branch as a dependency directly or downgrade to chart.js 2.8.x

**Closed by sgratzl** 2019-11-14 13:56 UTC
